/* Test-only legacy cards. Production never opts into these fixtures. */
export const learningTestModules = [
  {
    id: "module-1",
    title: "Модуль 1",
    description: "Первый модуль клуба. Внутри будут уроки и материалы первого блока.",
    defaultCardLayout: "vertical",
    images: [
      {
        id: "module-1-lesson-1",
        categoryId: "module-1",
        kind: "text",
        title: "Вариант 1. Плеер и очередь",
        url: "/previews/learning-redesign-1.svg",
        description: "Плеер, очередь просмотра и быстрый возврат к уроку.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/learning-redesign-1.svg",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      },
      {
        id: "module-1-lesson-2",
        categoryId: "module-1",
        kind: "text",
        title: "Вариант 2. Модули и уроки",
        url: "/previews/learning-redesign-2.svg",
        description: "Модульная структура с уроками внутри каждого блока.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/learning-redesign-2.svg",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "horizontal",
        isPersisted: false,
        archivedUntil: null
      },
      {
        id: "module-1-lesson-3",
        categoryId: "module-1",
        kind: "text",
        title: "Вариант 3. Библиотека",
        url: "/previews/learning-redesign-3.svg",
        description: "Библиотечный вид для быстрого поиска нужного урока.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/learning-redesign-3.svg",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      },
      {
        id: "module-1-lesson-4",
        categoryId: "module-1",
        kind: "text",
        title: "Вариант 4. Маршрут обучения",
        url: "/previews/learning-redesign-4.svg",
        description: "Маршрут прохождения с понятными шагами.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/learning-redesign-4.svg",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      }
    ],
    meta: "Модуль клуба",
    isPersisted: false
  },
  {
    id: "module-2",
    title: "Модуль 2",
    description: "Второй модуль клуба. Внутри будут уроки следующего блока.",
    defaultCardLayout: "vertical",
    images: [
      {
        id: "module-2-lesson-1",
        categoryId: "module-2",
        kind: "text",
        title: "Верх экрана",
        url: "/previews/admin-stats-preview-1.png",
        description: "Первый экран урока.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/admin-stats-preview-1.png",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      },
      {
        id: "module-2-lesson-2",
        categoryId: "module-2",
        kind: "text",
        title: "Оплаты и контент",
        url: "/previews/admin-stats-preview-2.png",
        description: "Экран с данными по оплатам и контенту.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/admin-stats-preview-2.png",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      },
      {
        id: "module-2-lesson-3",
        categoryId: "module-2",
        kind: "text",
        title: "Общение",
        url: "/previews/admin-stats-preview-3.png",
        description: "Экран с данными по общению.",
        content: "Здесь будет содержимое урока: текст, фото, видео, аудио или голосовое сообщение.",
        mediaUrl: null,
        mediaSource: null,
        thumbnailUrl: "/previews/admin-stats-preview-3.png",
        coverMode: "custom",
        coverSourceUrl: null,
        materials: [],
        cardLayout: "vertical",
        isPersisted: false,
        archivedUntil: null
      }
    ],
    meta: "Модуль клуба",
    isPersisted: false
  }
];

