import { nextTick, onBeforeUnmount, onMounted, watch, type Ref } from "vue";
import type { Locale } from "./i18n";

const englishPhrases: Record<string, string> = {
  "Загрузка урока": "Lesson upload",
  "Продолжить загрузку": "Continue upload",
  "Продолжаем загрузку": "Continuing upload",
  "Не закрывайте и не сворачивайте приложение": "Do not close or minimize the app",
  "Соединение прервалось": "Connection interrupted",
  "Хранилище временно недоступно": "Storage is temporarily unavailable",
  "Не удалось сохранить урок": "Could not save the lesson",
  "Этап": "Stage",
  "Попытки": "Attempts",
  "Время": "Time",
  "Основной файл": "Main file",
  "Обложка": "Cover",
  "Сохранение карточки": "Saving the lesson card",
  "Установить приложение": "Install app",
  "Установить": "Install",
  "Открываем...": "Opening...",
  "Добавить на главный экран": "Add to Home screen",
  "Сохранить и поделиться": "Save and share",
  "Установить страницу как приложение": "Install page as app",
  "Поделиться": "Share",
  "Добавить в Dock": "Add to Dock",
  "На экран Домой": "Add to Home Screen",
  "Добавить": "Add",
  "Код из письма": "Email code",
  "Вход в клуб": "Sign in to the club",
  "Введите 6 цифр из письма.": "Enter the 6-digit code from the email.",
  "Введите email, на который открыть доступ.": "Enter the email address for access.",
  "Код": "Code",
  "Войти": "Sign in",
  "Изменить email": "Change email",
  "Отправить код ещё раз": "Send code again",
  "Получить код": "Get code",
  "Закрыть предложение уведомлений": "Close notification prompt",
  "Включите уведомления": "Enable notifications",
  "Коды, ответы поддержки, оплаты и новости клуба будут приходить сразу в приложение.": "Codes, support replies, payments and club news will arrive directly in the app.",
  "Включить": "Enable",
  "Позже": "Later",
  "Закрыть подсказку установки": "Close installation guide",
  "Установите Club на Android": "Install Club on Android",
  "Откройте клуб через иконку приложения. После этого вход по email станет доступен.": "Open the club from the app icon. Email sign-in will then be available.",
  "Откройте сайт в Chrome на Android.": "Open the website in Chrome on Android.",
  "Нажмите меню Chrome ⋮ справа от адресной строки.": "Tap the Chrome menu ⋮ next to the address bar.",
  "Выберите “Добавить на главный экран”, затем “Установить”.": "Choose “Add to Home screen”, then “Install”.",
  "Откройте Club через новую иконку на телефоне.": "Open Club from the new icon on your phone.",
  "Как установить на Android": "How to install on Android",
  "Если кнопка установки не открылась, установите Club через меню Chrome.": "If the installation prompt did not open, install Club from the Chrome menu.",
  "Откройте меню Chrome ⋮.": "Open the Chrome menu ⋮.",
  "Нажмите “Добавить на главный экран”.": "Tap “Add to Home screen”.",
  "Выберите “Установить” и откройте новую иконку Club.": "Choose “Install” and open the new Club icon.",
  "Добавьте Club на экран Домой": "Add Club to your Home Screen",
  "На iPhone установка делается через меню Safari. После добавления клуб откроется без адресной строки, как обычное приложение.": "On iPhone, install Club from the Safari menu. It will then open without the address bar like a regular app.",
  "Откройте сайт в Safari на iPhone.": "Open the website in Safari on iPhone.",
  "Нажмите “Поделиться”.": "Tap “Share”.",
  "Выберите “На экран Домой”.": "Choose “Add to Home Screen”.",
  "Включите “Открывать как веб-приложение”, если такой пункт показан.": "Enable “Open as Web App” if this option is shown.",
  "Нажмите “Добавить” и откройте Club через новую иконку.": "Tap “Add” and open Club from the new icon.",
  "Как установить на iPhone": "How to install on iPhone",
  "iPhone не открывает системное окно установки по кнопке сайта. Используйте меню Safari.": "iPhone does not show the system installation prompt from a website button. Use the Safari menu.",
  "Откройте сайт в Safari.": "Open the website in Safari.",
  "Выберите “На экран Домой”, затем “Добавить”.": "Choose “Add to Home Screen”, then “Add”.",
  "Установите Club на Windows": "Install Club on Windows",
  "После установки Club появится в меню Пуск и откроется отдельным окном приложения.": "After installation, Club will appear in the Start menu and open in its own app window.",
  "Откройте сайт в Chrome или Edge.": "Open the website in Chrome or Edge.",
  "Нажмите иконку установки в адресной строке.": "Click the install icon in the address bar.",
  "Подтвердите “Установить”.": "Confirm “Install”.",
  "Откройте Club из меню Пуск или через созданную иконку.": "Open Club from the Start menu or the new icon.",
  "Как установить на Windows": "How to install on Windows",
  "Если окно установки не появилось, используйте меню браузера.": "If the installation prompt did not appear, use the browser menu.",
  "Установите Club на macOS": "Install Club on macOS",
  "На Mac Club можно добавить в Dock или установить через Chrome/Edge как отдельное приложение.": "On Mac, add Club to the Dock or install it from Chrome/Edge as a separate app.",
  "В Safari откройте сайт и нажмите “Поделиться” → “Добавить в Dock”.": "In Safari, open the website and choose “Share” → “Add to Dock”.",
  "В Chrome или Edge нажмите иконку установки в адресной строке.": "In Chrome or Edge, click the install icon in the address bar.",
  "Подтвердите установку.": "Confirm installation.",
  "Откройте Club из Dock, Launchpad или Spotlight.": "Open Club from the Dock, Launchpad or Spotlight.",
  "Как установить на macOS": "How to install on macOS",
  "Выберите инструкцию для браузера, которым открыт сайт.": "Choose the guide for your current browser.",
  "Установите Club как приложение": "Install Club as an app",
  "Откройте клуб через отдельную иконку приложения. В браузерной вкладке вход закрыт.": "Open the club from its app icon. Sign-in is unavailable in a regular browser tab.",
  "Админка": "Admin",
  "Статистика": "Statistics",
  "Клиенты": "Clients",
  "Платежи": "Payments",
  "История заказов, webhook и статусы оплат Prodamus.": "Order history, webhooks and Prodamus payment statuses.",
  "Всего заказов": "Total orders",
  "Оплачено": "Paid",
  "Разовые": "One-time",
  "Рекуррент": "Recurring",
  "Сумма оплат": "Total paid",
  "Оплачен": "Paid",
  "Разовый": "One-time",
  "Webhook: валидный": "Webhook: valid",
  "Webhook: ошибка подписи": "Webhook: signature error",
  "Webhook: не пришёл": "Webhook: not received",
  "Хранилище": "Storage",
  "S3-облако для фото, видео, аудио, голосовых и обложек.": "S3 storage for photos, videos, audio, voice messages and covers.",
  "Настройки проекта": "Project settings",
  "Админы": "Administrators",
  "Администраторы": "Administrators",
  "Доступ, роль вручную и права по всем разделам.": "Access, manually assigned roles and permissions for every section.",
  "Владелец клуба": "Club owner",
  "Полный доступ без ограничений.": "Full unrestricted access.",
  "Добавить администратора": "Add administrator",
  "Введите email или найдите клиента по имени, username либо ID.": "Enter an email or find a client by name, username or ID.",
  "Активен": "Active",
  "Журнал действий": "Audit log",
  "Действий пока нет": "No actions yet",
  "Сервер": "Server",
  "Состояние, ресурсы и ошибки API. Доступно разработчику.": "API status, resources and errors. Available to the developer.",
  "Работает": "Operational",
  "Процесс API": "API process",
  "Память Node": "Node memory",
  "Память сервера": "Server memory",
  "Диск": "Disk",
  "Нагрузка": "Load",
  "База данных": "Database",
  "Ручная резервная копия и восстановление PostgreSQL.": "Manual PostgreSQL backup and restore.",
  "Восстановление полностью заменит текущие данные клуба.": "Restoring will completely replace the current club data.",
  "Логи сервера": "Server logs",
  "Не Docker-логи. Только последние 100 ошибок API, список очищается после перезапуска сервера.": "Not Docker logs. Only the latest 100 API errors; the list is cleared after a server restart.",
  "S3 основное": "Primary S3",
  "S3 резервное": "Backup S3",
  "Подключено": "Connected",
  "Не подключено": "Not connected",
  "Статусы S3": "S3 status",
  "Обзор файлов": "File browser",
  "Открыть файлы по папкам.": "Browse files by folder.",
  "Настройки S3": "S3 settings",
  "Bucket, ключи и ссылки.": "Bucket, keys and URLs.",
  "Источник:": "Source:",
  "настройка из админки": "admin settings",
  "переменные сервера": "server environment",
  "не подключено": "not connected",
  "· изменено": "· updated",
  "· резерв:": "· backup:",
  "подключён": "connected",
  "не подключён": "not connected",
  "Реферальное вознаграждение": "Referral reward",
  "Общие параметры клуба. Доступно разработчику и администраторам с правом.": "General club settings. Available to the developer and authorized administrators.",
  "Реферальная система": "Referral system",
  "Сколько бонусных дней начислять пригласившему клиенту после первой оплаты приглашённого.": "Bonus days awarded to the referring client after the invited client's first payment.",
  "Аварийный вход по email": "Emergency email sign-in",
  "Создайте одноразовый код, если клиент не может получить письмо. Срок действия появится вместе с кодом.": "Create a one-time code if the client cannot receive the email. Its expiration time will be shown with the code.",
  "Дни копятся в профиле клиента и активируются вручную. При активной автоподписке активировать нельзя.": "Days accumulate in the client profile and are activated manually. They cannot be activated while a recurring subscription is active.",
  "Сохранить настройки": "Save settings",
  "Email клиента": "Client email",
  "Сгенерировать код": "Generate code",
  "Передать владение": "Transfer ownership",
  "email, имя или username": "email, name or username",
  "Показать журнал": "Show audit log",
  "Скачать базу": "Download database",
  "Файл резервной копии": "Backup file",
  "Файл формата .dump, скачанный из этой вкладки.": "A .dump file downloaded from this section.",
  "Подтверждение": "Confirmation",
  "Без этой фразы восстановление не запустится.": "Restore will not start without this phrase.",
  "Введите ВОССТАНОВИТЬ": "Enter RESTORE",
  "Восстановить базу": "Restore database",
  "Открыть логи": "Open logs",
  "Клиенты, доступ и ограничения.": "Clients, access and restrictions.",
  "Открыть список обновлений": "Open release notes",
  "Вид как": "View as",
  "Разраб": "Developer",
  "Админ": "Admin",
  "С доступом": "With access",
  "Без доступа": "No access",
  "Обновления": "Release notes",
  "История изменений приложения по версиям.": "Application changes by version.",
  "Закрыть список обновлений": "Close release notes",
  "Статистика клуба": "Club statistics",
  "Клиенты, оплаты, контент и общение по выбранному периоду.": "Clients, payments, content and community for the selected period.",
  "Период статистики": "Statistics period",
  "7 дней": "7 days",
  "30 дней": "30 days",
  "Период": "Period",
  "Всё время": "All time",
  "С": "From",
  "По": "To",
  "Выручка": "Revenue",
  "Новые клиенты": "New clients",
  "за выбранный период": "for the selected period",
  "Состояние на сегодня": "Current status",
  "активны": "active",
  "Финансы": "Finance",
  "За выбранный период": "For the selected period",
  "оплат": "payments",
  "Обучение": "Learning",
  "прогресс": "progress",
  "Общение": "Community",
  "сообщений": "messages",
  "Опросы": "Polls",
  "участников": "participants",
  "Клиенты и доступ": "Clients and access",
  "Поиск, продление доступа, быстрый мут и просмотр статистики.": "Search, access renewal, quick mute and statistics.",
  "Сводка по клиентам": "Client summary",
  "Быстрые фильтры клиентов": "Quick client filters",
  "Всего": "Total",
  "Ограничены": "Restricted",
  "Поиск по ID, имени или username": "Search by ID, name or username",
  "Все": "All",
  "Активные": "Active",
  "Закрыты": "Closed",
  "Дополнительные фильтры": "More filters",
  "Любой доступ": "Any access",
  "Доступ открыт": "Access open",
  "Доступ закрыт": "Access closed",
  "Доступ ограничен": "Access restricted",
  "Без тарифа": "No plan",
  "Все тарифы": "All plans",
  "Все клиенты": "All clients",
  "С ограничениями": "Restricted",
  "Сбросить": "Reset",
  "Email отключён": "Email disabled",
  "Последний вход": "Last login",
  "Доступ": "Access",
  "Оплаты": "Payments",
  "Последнее действие": "Last activity",
  "Нет активности": "No activity",
  "Написать клиенту": "Message client",
  "Для выдачи доступа нужно право Доступы.": "Access permission is required to manage access.",
  "Менять доступ и ограничения администраторов может только главный админ.": "Only the owner can change administrator access and restrictions.",
  "Действия с клиентом": "Client actions",
  "Действие": "Actions",
  "Открыть доступ": "Open access",
  "Открываю...": "Opening...",
  "Закрыть доступ": "Close access",
  "Закрываю...": "Closing...",
  "+7 дней": "+7 days",
  "+30 дней": "+30 days",
  "Продлеваю...": "Extending...",
  "Ручной доступ": "Manual access",
  "Дата окончания доступа": "Access end date",
  "Мут до снятия": "Mute until removed",
  "Сохраняю...": "Saving...",
  "Активность": "Activity",
  "последние события": "latest events",
  "время не сохранено": "time not saved",
  "Последних событий пока нет.": "No recent activity yet.",
  "Подписки": "Subscriptions",
  "Истории подписок пока нет.": "No subscription history yet.",
  "Оплаты клиента": "Client payments",
  "Оплат пока нет.": "No payments yet.",
  "Рефералы": "Referrals",
  "Пришёл по ссылке": "Joined by referral link",
  "первой оплаты ещё нет": "no first payment yet",
  "Реферальных связей пока нет.": "No referral relationships yet.",
  "оплаты ещё нет": "no payment yet",
  "Ограничения и удаления": "Restrictions and removals",
  "Ограничений и удалений пока нет.": "No restrictions or removals yet.",
  "Мут": "Mute",
  "Сообщение": "Message",
  "Комментарий": "Comment",
  "Снять мут": "Remove mute",
  "Устройства": "Devices",
  "Скопировать": "Copy",
  "История появится после следующего входа клиента.": "History will appear after the client's next login.",
  "IP входов": "Login IPs",
  "Загружаю историю IP…": "Loading IP history…",
  "Не удалось загрузить историю IP.": "Could not load IP history.",
  "История IP появится после следующего входа клиента.": "IP history will appear after the client's next login.",
  "Новый IP": "New IP",
  "Впервые": "First seen",
  "Входов": "Logins",
  "Сообщение клиенту": "Message client",
  "Закрыть сообщение клиенту": "Close client message",
  "Добавить файл": "Add file",
  "Напишите сообщение клиенту": "Write a message to the client",
  "Отправляем...": "Sending...",
  "Отправить": "Send",
  "Рассылки": "Mailings",
  "Push и email для выбранной аудитории.": "Push and email for the selected audience.",
  "Новая рассылка": "New mailing",
  "История": "History",
  "Обновить": "Refresh",
  "Повторить": "Repeat",
  "Тест себе": "Test to myself",
  "Пауза": "Pause",
  "Продолжить": "Resume",
  "Остановить": "Stop",
  "Рассылок пока нет.": "No mailings yet.",
  "Завершена": "Completed",
  "Запланирована": "Scheduled",
  "Отправляется": "Sending",
  "Остановлена": "Stopped",
  "Черновик": "Draft",
  "Текст, вложение, фильтры и планирование.": "Text, attachment, filters and scheduling.",
  "Сбросить форму": "Reset form",
  "Текст, HTML-форматирование, вложение, фильтры и планирование.": "Text, HTML formatting, attachment, filters and scheduling.",
  "Закрыть рассылку": "Close mailing",
  "Заголовок": "Title",
  "Например: Новая практика в клубе": "For example: New club practice",
  "Список": "List",
  "Ссылка": "Link",
  "Текст рассылки": "Mailing text",
  "Куда отправляем рассылку": "Mailing channels",
  "В приложение": "In app",
  "Колокольчик и PWA push": "Notification center and PWA push",
  "Письмо на почту": "Email message",
  "Оба канала": "Both channels",
  "Статус доступа": "Access status",
  "Тип доступа": "Access type",
  "Исключить админов": "Exclude admins",
  "Исключить ограничения": "Exclude restricted clients",
  "Запланировать": "Schedule",
  "Расчёт": "Estimate",
  "Сколько получателей попадёт в выбранные каналы.": "Recipients included in the selected channels.",
  "Пересчитать": "Recalculate",
  "Получателей": "Recipients",
  "Всего доставок": "Total deliveries",
  "PWA-подписок": "PWA subscriptions",
  "Email без адреса": "Missing email",
  "Отписались от email": "Unsubscribed from email",
  "Не прошли фильтры": "Filtered out",
  "Примерное время": "Estimated time",
  "считаем...": "calculating...",
  "Запланировать рассылку": "Schedule mailing",
  "Запустить рассылку": "Start mailing",
  "Рассылка": "Mailing",
  "Канал": "Channel",
  "Статус": "Status",
  "Отправлено": "Sent",
  "Фильтры": "Filters",
  "Вложение": "Attachment",
  "Без вложения": "No attachment",
  "Удалить все сообщения": "Delete all messages",
  "Удалить все сообщения?": "Delete all messages?",
  "Удалить всё": "Delete all",
  "Общение закрыто": "Community unavailable",
  "Раздел доступен после активации подписки.": "This section is available after activating a subscription.",
  "Название темы": "Topic title",
  "Добавить тему": "Add topic",
  "Вам ответили": "You have a reply",
  "Архив": "Archive",
  "Вернуть": "Restore",
  "Назад": "Back",
  "Тема закрыта": "Topic closed",
  "Открытый чат": "Open chat",
  "Меню чата": "Chat menu",
  "Открыть чат": "Open chat",
  "Закрыть чат": "Close chat",
  "Закреплено": "Pinned",
  "Удалено": "Deleted",
  "Скрыто": "Hidden",
  "Убрать ответ": "Cancel reply",
  "Отмена": "Cancel",
  "Остановить запись": "Stop recording",
  "Удалить": "Delete",
  "Отправка…": "Sending…",
  "Вложения": "Attachments",
  "Из галереи": "Choose from gallery",
  "Сделать фото": "Take photo",
  "Опрос": "Poll",
  "Эмодзи": "Emoji",
  "Записать голосовое": "Record voice message",
  "Действия с сообщением": "Message actions",
  "Открепить сообщение": "Unpin message",
  "Закрепить сообщение": "Pin message",
  "Удалить сообщение": "Delete message",
  "Вернуть сообщение": "Restore message",
  "Снять ограничение": "Remove restriction",
  "Ограничить до ручного снятия": "Restrict until manually removed",
  "Удалить все сообщения пользователя": "Delete all messages by user",
  "Редактировать тариф": "Edit plan",
  "Новый тариф": "New plan",
  "Обычный платеж или рекуррентная подписка.": "One-time payment or recurring subscription.",
  "Тип": "Type",
  "Обычный платеж": "One-time payment",
  "Рекуррентная подписка": "Recurring subscription",
  "Название": "Name",
  "Метка (необязательно)": "Badge (optional)",
  "Например: Выгодно": "For example: Best value",
  "Цена, ₽": "Price, RUB",
  "Дней доступа": "Access days",
  "Показывать клиентам": "Show to clients",
  "Тариф виден в разделе оплаты": "The plan is visible in Payments",
  "Тариф скрыт от клиентов": "The plan is hidden from clients",
  "Сохранить тариф": "Save plan",
  "Добавить тариф": "Add plan",
  "Скрыть тариф": "Hide plan",
  "Открыть тариф": "Show plan",
  "Удалить тариф": "Delete plan",
  "Добавить платежную систему": "Add payment provider",
  "Подключена. Можно изменить настройки.": "Connected. You can update the settings.",
  "Нажмите, чтобы подключить.": "Tap to connect.",
  "Данные платежной формы и URL уведомлений.": "Payment form data and notification URL.",
  "URL платежной формы": "Payment form URL",
  "Секретный ключ": "Secret key",
  "Платежная система включена": "Payment provider enabled",
  "URL уведомлений": "Notification URL",
  "Закрыть": "Close",
  "Сохранить": "Save",
  "Подключить": "Connect",
  "Редактировать модуль": "Edit module",
  "Новый модуль": "New module",
  "Название, описание и формат карточек модуля.": "Module name, description and card layout.",
  "Измените название, описание и формат карточек.": "Update the name, description and card layout.",
  "Добавить модуль": "Add module",
  "Управление модулями": "Manage modules",
  "Сортировка модуля": "Module sorting",
  "Поднять модуль": "Move module up",
  "Опустить модуль": "Move module down",
  "Удалённый контент": "Deleted content",
  "Системный модуль": "System module",
  "Хранится 7 дней после удаления. Можно восстановить прямо из карточки.": "Stored for 7 days after deletion. You can restore it from the card.",
  "Восстановить": "Restore",
  "Название модуля": "Module name",
  "Например: Модуль 3": "For example: Module 3",
  "Описание модуля": "Module description",
  "Коротко о том, что внутри": "Briefly describe the module",
  "Какие карточки создавать": "Default card layout",
  "Тип карточек модуля": "Module card layout",
  "Вертикальные": "Vertical",
  "Горизонтальные": "Horizontal",
  "Вертикальные уроки": "Vertical lessons",
  "Горизонтальные уроки": "Horizontal lessons",
  "Сохранить модуль": "Save module",
  "Вид карточки": "Card layout",
  "Горизонтальная карточка": "Horizontal card",
  "Вертикальная карточка": "Vertical card",
  "Формат карточек задан в настройках модуля.": "The card layout is set in module settings.",
  "Название урока": "Lesson title",
  "Например: Первый урок": "For example: First lesson",
  "Описание урока": "Lesson description",
  "Короткое описание": "Short description",
  "Тип урока": "Lesson type",
  "Источник контента": "Content source",
  "Файл урока": "Lesson file",
  "Ссылка на файл": "File URL",
  "Файл не выбран": "No file selected",
  "Файл в S3 загружаться не будет.": "The file will not be uploaded to S3.",
  "Записать голос": "Record voice",
  "Обложка карточки (не обязательно)": "Card cover (optional)",
  "Обложка карточки": "Card cover",
  "Источник обложки": "Cover source",
  "Стандартная": "Standard",
  "Своя": "Custom",
  "Первое вложение": "First attachment",
  "Своя обложка (не обязательно)": "Custom cover (optional)",
  "Удалить обложку": "Remove cover",
  "Содержимое урока": "Lesson content",
  "Текст урока или описание вложений": "Lesson text or attachment description",
  "Дополнительные материалы": "Additional materials",
  "Текст, фото, видео или аудио внутри этого урока.": "Text, photo, video or audio within this lesson.",
  "Добавить ещё материал": "Add another material",
  "Материал": "Material",
  "Удалить дополнительный материал": "Delete additional material",
  "Название материала": "Material title",
  "Например: Разбор задания": "For example: Task review",
  "Описание": "Description",
  "Источник материала": "Material source",
  "Файл материала": "Material file",
  "Текст / заметка": "Text / note",
  "Текст материала или комментарий к файлу": "Material text or file note",
  "Удалить урок": "Delete lesson",
  "Сохранить урок": "Save lesson",
  "Сохраняем...": "Saving...",
  "Просмотр изображения": "Image viewer",
  "Закрыть изображение": "Close image",
  "Передать клуб выбранному администратору?": "Transfer the club to the selected administrator?",
  "После подтверждения выбранный администратор сразу станет владельцем и получит полный контроль над клубом.":
    "After confirmation, the selected administrator will immediately become the owner and gain full control of the club.",
  "Да, передать клуб": "Yes, transfer the club"
};

const englishPatterns: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^(\d+) клиентов$/, (count) => `${count} clients`],
  [/^(\d+) сообщений$/, (count) => `${count} messages`],
  [/^(\d+) оплат$/, (count) => `${count} payments`],
  [/^(\d+) оплат за выбранный период$/, (count) => `${count} payments for the selected period`],
  [/^(\d+) участников$/, (count) => `${count} participants`],
  [/^(\d+) записей$/, (count) => `${count} records`],
  [/^(\d+) файлов$/, (count) => `${count} files`],
  [/^Найдено: (\d+)$/, (count) => `Found: ${count}`],
  [/^(\d+) рассылок$/, (count) => `${count} mailings`],
  [/^(\d+) доставок$/, (count) => `${count} deliveries`],
  [/^(.+) доставок$/, (count) => `${count} deliveries`],
  [/^(.+) · Завершена$/, (channel) => `${channel} · Completed`],
  [/^около (\d+) секунд$/, (count) => `about ${count} seconds`],
  [/^(\d+) сохранено$/, (count) => `${count} saved`],
  [/^(\d+) адресов$/, (count) => `${count} addresses`],
  [/^(\d+) приглашённых$/, (count) => `${count} invited`],
  [/^Запись (\d+) сек\.$/, (count) => `Recording ${count} sec.`],
  [/^Отправить (\d+)$/, (count) => `Send ${count}`],
  [/^Отправить код ещё раз через (\d+)с$/, (count) => `Send code again in ${count}s`],
  [/^Получить код через (\d+)с$/, (count) => `Get code in ${count}s`],
  [/^Удалить изображение (\d+)$/, (count) => `Delete image ${count}`],
  [/^Открыть изображение материала (\d+)$/, (count) => `Open material image ${count}`],
  [/^Открыть изображение (.+)$/, (title) => `Open image ${title}`],
  [/^Уроки (\d+)\/(\d+)$/, (done, total) => `Lessons ${done}/${total}`],
  [/^Вход (.+)$/, (date) => `Login ${date}`],
  [/^до (.+)$/, (date) => `until ${date}`],
  [/^Впервые: (.+)$/, (date) => `First seen: ${date}`],
  [/^Последний вход: (.+)$/, (date) => `Last login: ${date}`],
  [/^Входов: (\d+)$/, (count) => `Logins: ${count}`],
  [/^Проверено (.+)$/, (date) => `Checked ${date}`],
  [/^(\d+) ч\. (\d+) мин\.$/, (hours, minutes) => `${hours} h ${minutes} min`],
  [/^(\d+) ошибок в памяти$/, (count) => `${count} errors in memory`],
  [/^Владелец · (.+)$/, (name) => `Owner · ${name}`],
  [/^Источник: настройка из админки · изменено (.+) · резерв: не подключён$/, (date) => `Source: admin settings · updated ${date} · backup: not connected`],
  [/^Развернуть (.+)$/, (title) => `Expand ${title}`],
  [/^Свернуть (.+)$/, (title) => `Collapse ${title}`],
  [/^Редактировать (.+)$/, (title) => `Edit ${title}`],
  [/^Переключить (.+)$/, (title) => `Toggle ${title}`],
  [/^Добавить урок в (.+)$/, (title) => `Add lesson to ${title}`],
  [/^Добавить карточку в (.+)$/, (title) => `Add card to ${title}`],
  [/^Открыть урок (.+)$/, (title) => `Open lesson ${title}`],
  [/^Удалить категорию "(.+)" и весь контент внутри неё\?$/, (title) => `Delete category “${title}” and all of its content?`],
  [/^Удалить контент "(.+)"\?$/, (title) => `Delete content “${title}”?`],
  [/^Удалить модуль "(.+)" вместе с уроками\?$/, (title) => `Delete module “${title}” and its lessons?`],
  [/^Удалить урок "(.+)"\? Он попадет в удалённые на 7 дней\.$/, (title) => `Delete lesson “${title}”? It will remain in Deleted content for 7 days.`],
  [/^Удалить тариф "(.+)"\? Он попадет в архив на 7 дней\.$/, (title) => `Delete plan “${title}”? It will remain archived for 7 days.`],
  [/^Точно скрыть тариф "(.+)"\?$/, (title) => `Hide plan “${title}”?`],
  [/^Точно открыть тариф "(.+)"\?$/, (title) => `Show plan “${title}”?`],
  [/^Отменить подписку "(.+)"\?$/, (title) => `Cancel subscription “${title}”?`],
  [/^Восстановить подписку "(.+)"\?$/, (title) => `Restore subscription “${title}”?`],
  [/^Удалить все сообщения пользователя (.+) в этом чате\?$/, (name) => `Delete all messages by ${name} in this chat?`]
];

const partialEnglishPhrases: Array<[string, string]> = [
  ["МБ", "MB"],
  ["ГБ", "GB"],
  ["Владелец ·", "Owner ·"],
  ["настройка из админки", "admin settings"],
  ["переменные сервера", "server environment"],
  ["не подключён", "not connected"],
  ["Источник:", "Source:"],
  ["· изменено", "· updated"],
  ["· резерв:", "· backup:"]
];

export function translateInterfaceText(value: string, locale: Locale) {
  if (locale !== "en" || !/[А-Яа-яЁё]/.test(value)) return value;
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const source = value.trim();
  const normalizedSource = source.replace(/\s+/g, " ");
  const exact = englishPhrases[normalizedSource];
  if (exact) return `${leading}${exact}${trailing}`;

  for (const [pattern, formatter] of englishPatterns) {
    const match = normalizedSource.match(pattern);
    if (match) return `${leading}${formatter(...match.slice(1))}${trailing}`;
  }
  let partial = normalizedSource;
  for (const [russian, english] of partialEnglishPhrases) partial = partial.replaceAll(russian, english);
  if (partial !== normalizedSource) return `${leading}${partial}${trailing}`;
  return value;
}

const localizedAttributes = ["aria-label", "placeholder", "title", "data-placeholder"] as const;
const userContentSelector = ".chat-message-body, .chat-message-text, .lesson-rich-text, .support-message-content, [data-user-content]";

export function useInterfaceLocalization(locale: Ref<Locale>) {
  let observer: MutationObserver | null = null;
  let originalConfirm: typeof window.confirm | null = null;
  let originalPrompt: typeof window.prompt | null = null;
  const textSources = new WeakMap<Text, string>();
  const attributeSources = new WeakMap<Element, Map<string, string>>();

  const localizeTextNode = (node: Text) => {
    if (node.parentElement?.closest(userContentSelector)) return;
    const previous = textSources.get(node);
    if (previous === undefined || translateInterfaceText(previous, "en") !== node.data) textSources.set(node, node.data);
    const source = textSources.get(node) ?? node.data;
    const translated = translateInterfaceText(source, locale.value);
    if (node.data !== translated) node.data = translated;
  };

  const localizeElement = (element: Element) => {
    let sources = attributeSources.get(element);
    if (!sources) {
      sources = new Map();
      attributeSources.set(element, sources);
    }
    for (const attribute of localizedAttributes) {
      const current = element.getAttribute(attribute);
      if (current === null) continue;
      const saved = sources.get(attribute);
      if (saved === undefined || translateInterfaceText(saved, "en") !== current) sources.set(attribute, current);
      const source = sources.get(attribute) ?? current;
      const translated = translateInterfaceText(source, locale.value);
      if (current !== translated) element.setAttribute(attribute, translated);
    }
    for (const child of element.childNodes) {
      if (child.nodeType === Node.TEXT_NODE) localizeTextNode(child as Text);
      else if (child.nodeType === Node.ELEMENT_NODE) localizeElement(child as Element);
    }
  };

  const localizeDocument = () => {
    if (document.body) localizeElement(document.body);
  };

  onMounted(() => {
    originalConfirm = window.confirm.bind(window);
    originalPrompt = window.prompt.bind(window);
    window.confirm = (message?: string) => originalConfirm!(translateInterfaceText(String(message ?? ""), locale.value));
    window.prompt = (message?: string, defaultValue?: string) => originalPrompt!(translateInterfaceText(String(message ?? ""), locale.value), defaultValue);
    localizeDocument();
    observer = new MutationObserver((mutations) => {
      observer?.disconnect();
      for (const mutation of mutations) {
        if (mutation.type === "characterData") localizeTextNode(mutation.target as Text);
        else if (mutation.type === "attributes") localizeElement(mutation.target as Element);
        else for (const node of mutation.addedNodes) {
          if (node.nodeType === Node.TEXT_NODE) localizeTextNode(node as Text);
          else if (node.nodeType === Node.ELEMENT_NODE) localizeElement(node as Element);
        }
      }
      observer?.observe(document.body, { attributes: true, attributeFilter: [...localizedAttributes], characterData: true, childList: true, subtree: true });
    });
    observer.observe(document.body, { attributes: true, attributeFilter: [...localizedAttributes], characterData: true, childList: true, subtree: true });
  });

  watch(locale, () => nextTick(localizeDocument));
  onBeforeUnmount(() => {
    observer?.disconnect();
    if (originalConfirm) window.confirm = originalConfirm;
    if (originalPrompt) window.prompt = originalPrompt;
  });
}
